In [7]:
import pandas as pd

In [9]:
df = pd.read_csv("teleCust.csv")

In [11]:
df

region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9      64   4       5       0   
1         3      11   33        1        7     136   5       5       0   
2         3      68   52        1       24     116   1      29       0   
3         2      33   33        0       12      33   2       0       0   
4         2      23   30        1        9      30   1       2       0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0      27   3       0       0   
996       1       7   34        0        2      22   5       5       0   
997       3      67   59        0       40     944   5      33       0   
998       3      70   49        0       18      87   2      22       0   
999       3      50   36        1        7      39   3       3       0   

     gender  reside  custcat  
0         0       2        1  
1         0       6        4  
2         1       2        3  
3         1       1        1  
4         0       4        3  
..      ...     ...      ...  
995       1       3        1  
996       1       1        1  
997       1       1        4  
998       1       1        3  
999       1       3        2  

[1000 rows x 12 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   region   1000 non-null   int64
 1   tenure   1000 non-null   int64
 2   age      1000 non-null   int64
 3   marital  1000 non-null   int64
 4   address  1000 non-null   int64
 5   income   1000 non-null   int64
 6   ed       1000 non-null   int64
 7   employ   1000 non-null   int64
 8   retire   1000 non-null   int64
 9   gender   1000 non-null   int64
 10  reside   1000 non-null   int64
 11  custcat  1000 non-null   int64
dtypes: int64(12)
memory usage: 93.9 KB


In [17]:
df.isna().sum()

region     0
tenure     0
age        0
marital    0
address    0
income     0
ed         0
employ     0
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [21]:
df.custcat.value_counts()

custcat
3    281
1    266
4    236
2    217
Name: count, dtype: int64

In [34]:
features = df.drop('custcat', axis=1)

In [36]:
features

region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9      64   4       5       0   
1         3      11   33        1        7     136   5       5       0   
2         3      68   52        1       24     116   1      29       0   
3         2      33   33        0       12      33   2       0       0   
4         2      23   30        1        9      30   1       2       0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0      27   3       0       0   
996       1       7   34        0        2      22   5       5       0   
997       3      67   59        0       40     944   5      33       0   
998       3      70   49        0       18      87   2      22       0   
999       3      50   36        1        7      39   3       3       0   

     gender  reside  
0         0       2  
1         0       6  
2         1       2  
3         1       1  
4         0       4  
..      ...     ...  
995       1       3  
996       1       1  
997       1       1  
998       1       1  
999       1       3  

[1000 rows x 11 columns]

In [38]:
target = df.custcat

In [40]:
target

0      1
1      4
2      3
3      1
4      3
      ..
995    1
996    1
997    4
998    3
999    2
Name: custcat, Length: 1000, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

In [52]:
x_train, x_test, y_train, y_test = train_test_split(features,target,test_size=0.25,random_state=101)

In [61]:
from sklearn.neighbors import KNeighborsClassifier

In [80]:
model = KNeighborsClassifier(n_neighbors = 3)

In [82]:
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [84]:
y_pred = model.predict(x_test)

In [86]:
y_pred

array([1, 4, 3, 1, 1, 4, 1, 2, 1, 4, 2, 2, 4, 1, 1, 2, 2, 2, 1, 1, 1, 1,
       1, 2, 1, 3, 4, 2, 4, 1, 4, 3, 1, 1, 1, 3, 1, 1, 2, 1, 4, 1, 3, 3,
       2, 1, 3, 1, 1, 1, 3, 4, 1, 1, 1, 2, 1, 4, 4, 1, 3, 3, 3, 1, 4, 3,
       1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 4, 2, 3, 2, 3, 1, 3, 1, 1, 2,
       1, 2, 1, 4, 1, 1, 3, 2, 3, 1, 3, 4, 3, 3, 4, 2, 1, 2, 4, 1, 2, 3,
       1, 1, 1, 1, 2, 2, 1, 1, 4, 2, 2, 3, 1, 1, 3, 2, 4, 4, 1, 1, 2, 1,
       2, 1, 1, 3, 1, 1, 4, 1, 1, 2, 3, 1, 1, 2, 1, 2, 2, 2, 2, 1, 4, 3,
       3, 1, 3, 2, 2, 1, 1, 3, 4, 1, 1, 2, 1, 2, 1, 1, 2, 2, 2, 3, 1, 2,
       1, 3, 4, 3, 2, 4, 3, 2, 3, 2, 4, 1, 1, 1, 3, 1, 4, 1, 1, 4, 1, 3,
       3, 2, 1, 3, 1, 2, 1, 2, 1, 3, 1, 2, 2, 3, 1, 4, 1, 2, 2, 1, 2, 4,
       3, 1, 3, 1, 1, 1, 1, 4, 3, 3, 3, 1, 4, 1, 2, 2, 3, 1, 4, 4, 1, 2,
       2, 1, 3, 3, 1, 2, 4, 1], dtype=int64)

In [88]:
from sklearn.metrics import classification_report

In [90]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.27      0.48      0.35        61
           2       0.31      0.33      0.32        58
           3       0.29      0.22      0.25        64
           4       0.34      0.18      0.24        67

    accuracy                           0.30       250
   macro avg       0.30      0.30      0.29       250
weighted avg       0.31      0.30      0.29       250



In [103]:
import numpy as np
np.expand_dims(features.to_numpy()[0], axis = 0)



array([[ 2, 13, 44,  1,  9, 64,  4,  5,  0,  0,  2]], dtype=int64)

In [105]:
model.predict(np.expand_dims(features.to_numpy()[0], axis = 0))

C:\Users\PALLAVI\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([4], dtype=int64)